/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'id' : bigint,
  'clubId' : [] | [bigint],
  'action' : string,
  'actorName' : string,
  'timestamp' : bigint,
}
export interface Club {
  'id' : bigint,
  'name' : string,
  'slug' : string,
  'description' : string,
}
export interface GitHubProject {
  'id' : bigint,
  'title' : string,
  'authorName' : string,
  'description' : string,
  'timestamp' : bigint,
  'repoUrl' : string,
}
export interface Notification {
  'id' : bigint,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'relatedPostId' : [] | [bigint],
}
export interface Post {
  'id' : bigint,
  'title' : string,
  'clubId' : [] | [bigint],
  'body' : string,
  'authorName' : string,
  'imageUrl' : [] | [string],
  'timestamp' : bigint,
  'category' : PostCategory,
  'eventDate' : [] | [bigint],
}
export type PostCategory = { 'Event' : null } |
  { 'Announcement' : null } |
  { 'Update' : null };
export interface UserProfile {
  'bio' : string,
  'portfolio' : string,
  'linkedIn' : string,
  'branch' : string,
  'name' : string,
  'role' : string,
  'year' : string,
  'email' : string,
  'contactEmail' : string,
  'github' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGitHubProject' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllData' : ActorMethod<[], undefined>,
  'createPost' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [bigint],
      string,
      bigint,
      [] | [bigint],
      [] | [string],
    ],
    bigint
  >,
  'getAllClubPosts' : ActorMethod<[], Array<Post>>,
  'getAllClubs' : ActorMethod<[], Array<Club>>,
  'getAllGitHubProjects' : ActorMethod<[], Array<GitHubProject>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPostsByCategory' : ActorMethod<[PostCategory], Array<Post>>,
  'getPostsByClub' : ActorMethod<[bigint], Array<Post>>,
  'getRecentPosts' : ActorMethod<[bigint], Array<Post>>,
  'getSortedActivityFeed' : ActorMethod<[], Array<ActivityEntry>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUpcomingEvents' : ActorMethod<[], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'preSeedData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];