/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostCategory = IDL.Variant({
  'Event' : IDL.Null,
  'Announcement' : IDL.Null,
  'Update' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'clubId' : IDL.Opt(IDL.Nat),
  'body' : IDL.Text,
  'authorName' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'category' : PostCategory,
  'eventDate' : IDL.Opt(IDL.Int),
});
export const Club = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
});
export const GitHubProject = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'repoUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'portfolio' : IDL.Text,
  'linkedIn' : IDL.Text,
  'branch' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'year' : IDL.Text,
  'email' : IDL.Text,
  'contactEmail' : IDL.Text,
  'github' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'relatedPostId' : IDL.Opt(IDL.Nat),
});
export const ActivityEntry = IDL.Record({
  'id' : IDL.Nat,
  'clubId' : IDL.Opt(IDL.Nat),
  'action' : IDL.Text,
  'actorName' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGitHubProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllData' : IDL.Func([], [], []),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllClubPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
  'getAllGitHubProjects' : IDL.Func([], [IDL.Vec(GitHubProject)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPostsByCategory' : IDL.Func([PostCategory], [IDL.Vec(Post)], ['query']),
  'getPostsByClub' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getRecentPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getSortedActivityFeed' : IDL.Func([], [IDL.Vec(ActivityEntry)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'preSeedData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostCategory = IDL.Variant({
    'Event' : IDL.Null,
    'Announcement' : IDL.Null,
    'Update' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'clubId' : IDL.Opt(IDL.Nat),
    'body' : IDL.Text,
    'authorName' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'category' : PostCategory,
    'eventDate' : IDL.Opt(IDL.Int),
  });
  const Club = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
  });
  const GitHubProject = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'repoUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'portfolio' : IDL.Text,
    'linkedIn' : IDL.Text,
    'branch' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'year' : IDL.Text,
    'email' : IDL.Text,
    'contactEmail' : IDL.Text,
    'github' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'relatedPostId' : IDL.Opt(IDL.Nat),
  });
  const ActivityEntry = IDL.Record({
    'id' : IDL.Nat,
    'clubId' : IDL.Opt(IDL.Nat),
    'action' : IDL.Text,
    'actorName' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGitHubProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllData' : IDL.Func([], [], []),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllClubPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
    'getAllGitHubProjects' : IDL.Func([], [IDL.Vec(GitHubProject)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPostsByCategory' : IDL.Func([PostCategory], [IDL.Vec(Post)], ['query']),
    'getPostsByClub' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getRecentPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getSortedActivityFeed' : IDL.Func([], [IDL.Vec(ActivityEntry)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'preSeedData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };